#!/usr/bin/env bash
# redirect permanent

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com permanent;/" /etc/nginx/sites-available/default
service nginx start
