#!/usr/bin/env bash
# redirect permanent

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
red="root /var/www/html;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/root /var/www/html;/$red/" /etc/nginx/sites-available/default
service nginx restart
