#!/usr/bin/env bash
#second server installation nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "15i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart