#!/usr/bin/env bash
#This script will print a string 10 times with if statemnt
c=10
while [  $c -gt 0 ];
do
    if [ $c -eq 1 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"
    let c-=1
done
