#!/usr/bin/env bash
#This script will print a string 10 times with if statemnt
c=1
while [  $c -lt 21 ];
do
    case $c in
	5)
	    echo "bad luck from China "
	    ;;
	10)
	    echo "bad luck from Japan"
	    ;;
	18)
	    echo "bad luck from Italy"
	    ;;
    esac
    echo $c
    let c+=1
done
