#!/usr/bin/env bash
#This script to print inlooop with case statemnt
c=0
while [  $((c++)) -lt 20 ];
do
    case $c in
	5)
	    echo "bad luck from China"
	    ;;
	10)
	    echo "bad luck from Japan"
	    ;;
	18)
	    echo "bad luck from Italy"
	    ;;
    esac
    echo $c
done
