#!/usr/bin/env bash
#This script to print inlooop with case statemnt
m=0
h=0
echo Hour: $h
while [  $((h++)) -lt 12 ];
do
    m=0
    while [  $((m++)) -lt 59 ];
    do
	echo $m
    done
    echo Hour: $h
done
